
POST http://127.0.0.1:8000/api/signup/
Content-Type: application/json

{"username": "Emil3", "password": "Emil3", "email":  "emil3wiklund@hotmail.com"}


###
POST http://127.0.0.1:8000/api/login/
Content-Type: application/json

{"username": "admin", "password": "admin"}


###
GET http://127.0.0.1:8000/api/validate/
Content-Type: application/json
Authorization: Token dddacc98f6e944326e1554ca078382f8eb54c33b

###
POST http://127.0.0.1:8000/api/logout/
Content-Type: application/json
Authorization: Token dddacc98f6e944326e1554ca078382f8eb54c33b

###
POST http://127.0.0.1:8000/api/createpost/
Content-Type: application/json
Authorization: Token 83f28346dd09b3e8fdc57c19ef09a5ea645c9462

{"moviequery" : "Lord"}

###
POST http://127.0.0.1:8000/api/post/upvote/32/
Content-Type: application/json
Authorization: Token dddacc98f6e944326e1554ca078382f8eb54c33b

{}
###
POST http://127.0.0.1:8000/api/post/downvote/31/
Content-Type: application/json
Authorization: Token dddacc98f6e944326e1554ca078382f8eb54c33b

{}


