
POST http://127.0.0.1:8000/api/signup/
Content-Type: application/json

{"username": "Emil2", "password": "Emil2", "email":  "emil2wiklund@hotmail.com"}


###
POST http://127.0.0.1:8000/api/login/
Content-Type: application/json

{"username": "admin", "password": "admin"}


###
GET http://127.0.0.1:8000/api/validate/
Content-Type: application/json
Authorization: Token 74ec776fb97547dab7abd4b6f6d66ba3f2c758eb

###
POST http://127.0.0.1:8000/api/logout/
Content-Type: application/json
Authorization: Token 74ec776fb97547dab7abd4b6f6d66ba3f2c758eb

###
POST http://127.0.0.1:8000/api/createpost/
Content-Type: application/json
Authorization: Token 74ec776fb97547dab7abd4b6f6d66ba3f2c758eb

{"moviequery" : "Lord"}

###
POST http://127.0.0.1:8000/api/post/upvote/28/
Content-Type: application/json
Authorization: Token 74ec776fb97547dab7abd4b6f6d66ba3f2c758eb

{}
###
POST http://127.0.0.1:8000/api/post/downvote/28/
Content-Type: application/json
Authorization: Token 74ec776fb97547dab7abd4b6f6d66ba3f2c758eb

{}


