
POST http://127.0.0.1:8000/api/signup/
Content-Type: application/json

{"username": "Emil2", "password": "Emil2", "email":  "emil2wiklund@hotmail.com"}


###
POST http://127.0.0.1:8000/api/login/
Content-Type: application/json

{"username": "admin", "password": "admin"}


###
GET http://127.0.0.1:8000/api/validate/
Content-Type: application/json
Authorization: Token 9e327285b1763549b6b97489350c5f2618eaea2f

###
POST http://127.0.0.1:8000/api/logout/
Content-Type: application/json
Authorization: Token 9e327285b1763549b6b97489350c5f2618eaea2f

###
POST http://127.0.0.1:8000/api/createpost/
Content-Type: application/json
Authorization: Token 9e327285b1763549b6b97489350c5f2618eaea2f

{"moviequery" : "Black Adam"}
