# Generated by Django 4.2.7 on 2023-11-15 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postId', models.IntegerField(unique=True)),
                ('postMetadata', models.CharField(help_text='Contain the data for the post.', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(unique=True)),
                ('userName', models.CharField(max_length=28)),
                ('userSurname', models.CharField(max_length=28)),
                ('userForename', models.CharField(max_length=28)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=16)),
                ('roleUserId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='movieRater.user')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratingId', models.IntegerField(unique=True)),
                ('ratingRating', models.IntegerField(help_text='Value from 0-5')),
                ('ratingComment', models.CharField(max_length=300)),
                ('ratingPost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='movieRater.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='postUserId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='movieRater.user'),
        ),
    ]
