# Generated by Django 4.2.4 on 2023-11-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieRater', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postMovieId',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
