# Generated by Django 4.2.7 on 2023-11-28 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movieRater', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='postMetadata',
            new_name='metadata',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='ratingComment',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='ratingPost',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='ratingRating',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='post',
            name='postId',
        ),
        migrations.RemoveField(
            model_name='post',
            name='postUserId',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='ratingId',
        ),
        migrations.RemoveField(
            model_name='role',
            name='roleUserId',
        ),
        migrations.AddField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='movie',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='role',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
