<<<<<<< HEAD
# Generated by Django 4.2.4 on 2023-11-16 09:33
=======
# Generated by Django 4.2.7 on 2023-11-16 10:08
>>>>>>> d4c584529df11883041771ca0f1e682a567369fc

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieRater', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postMovieId',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
