# Generated by Django 4.2.7 on 2023-12-08 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieRater', '0002_rename_postmetadata_post_metadata_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
