# Generated by Django 4.2.7 on 2023-12-12 09:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movieRater', '0003_delete_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AddField(
            model_name='post',
            name='downvotes',
            field=models.ManyToManyField(related_name='downvotedposts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='uppvotes',
            field=models.ManyToManyField(related_name='uppvotedposts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
